/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Core;

/**
 *
 * @author 1001503
 */
public class OptionMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form optionPanel
     */
    public OptionMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fwdKBL = new javax.swing.JFormattedTextField();
        leftKBL = new javax.swing.JFormattedTextField();
        rightKBL = new javax.swing.JFormattedTextField();
        spellKBL = new javax.swing.JFormattedTextField();
        eatKBL = new javax.swing.JFormattedTextField();
        potionKBL = new javax.swing.JFormattedTextField();
        invKBL = new javax.swing.JFormattedTextField();
        backBKL = new javax.swing.JFormattedTextField();
        apply = new javax.swing.JButton();
        defaultKB = new javax.swing.JButton();
        back = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(750, 500));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel1.setText("Forward Directional Keybind");
        add(jLabel1);
        jLabel1.setBounds(10, 11, 227, 19);

        jLabel2.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel2.setText("Backwards Directional Keybind");
        add(jLabel2);
        jLabel2.setBounds(10, 51, 249, 19);

        jLabel3.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel3.setText("Left Directional Keybind");
        add(jLabel3);
        jLabel3.setBounds(10, 91, 194, 19);

        jLabel4.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel4.setText("Right Directional Keybind");
        add(jLabel4);
        jLabel4.setBounds(10, 131, 205, 19);

        jLabel5.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel5.setText("Use Spell Keybind");
        add(jLabel5);
        jLabel5.setBounds(10, 171, 145, 19);

        jLabel6.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel6.setText("Eat Food Keybind");
        add(jLabel6);
        jLabel6.setBounds(10, 211, 139, 19);

        jLabel7.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel7.setText("Drink Potion Keybind");
        add(jLabel7);
        jLabel7.setBounds(10, 251, 169, 19);

        jLabel8.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel8.setText("Inventory Keybind");
        add(jLabel8);
        jLabel8.setBounds(10, 291, 147, 19);

        fwdKBL.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        add(fwdKBL);
        fwdKBL.setBounds(282, 12, 100, 21);

        leftKBL.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        add(leftKBL);
        leftKBL.setBounds(282, 92, 100, 21);

        rightKBL.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        add(rightKBL);
        rightKBL.setBounds(282, 132, 100, 21);

        spellKBL.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        add(spellKBL);
        spellKBL.setBounds(282, 172, 100, 21);

        eatKBL.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        add(eatKBL);
        eatKBL.setBounds(282, 212, 100, 21);

        potionKBL.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        add(potionKBL);
        potionKBL.setBounds(282, 252, 100, 21);

        invKBL.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        add(invKBL);
        invKBL.setBounds(282, 292, 100, 21);

        backBKL.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        add(backBKL);
        backBKL.setBounds(282, 52, 100, 21);

        apply.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        apply.setText("Apply");
        add(apply);
        apply.setBounds(510, 30, 120, 27);

        defaultKB.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        defaultKB.setText("Default Keybinds");
        add(defaultKB);
        defaultKB.setBounds(490, 90, 170, 27);

        back.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back);
        back.setBounds(520, 150, 110, 27);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton apply;
    public javax.swing.JButton back;
    public javax.swing.JFormattedTextField backBKL;
    public javax.swing.JButton defaultKB;
    public javax.swing.JFormattedTextField eatKBL;
    public javax.swing.JFormattedTextField fwdKBL;
    public javax.swing.JFormattedTextField invKBL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JFormattedTextField leftKBL;
    public javax.swing.JFormattedTextField potionKBL;
    public javax.swing.JFormattedTextField rightKBL;
    public javax.swing.JFormattedTextField spellKBL;
    // End of variables declaration//GEN-END:variables
}
