/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Render;

import Core.Main;
import Entity.Mob.Bandit;
import Entity.Mob.Snake;
import Level.Level;

/**
 *
 * @author Torri
 */
public class TextRender extends javax.swing.JPanel {
    Level l;
    int[][] pos;
    char[] type;
    int in;
    /**
     * Creates new form TextRender
     */
    public TextRender() {
        initComponents();
    }
    public void turn(){
        //l=Main.getGame().getCurrentLevel();
        pos = new int[l.getEntities().length][2];
        for(int i=0;i<l.getEntities().length;i++){
            pos[i][0] = l.getEntities()[i].x;
            pos[i][1] = l.getEntities()[i].y;
            if(l.getEntities()[i] instanceof Snake){
                type[i] = 'S';
            }else if(l.getEntities()[i] instanceof Bandit){
                type[i] = 'B';
            }else{
                type[i] = '.';
            }
        }
        for(int i=0;i<l.size;i++){
            for(int j=0;j<pos.length;j++){
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapTab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        dungeon = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        map = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        inventory = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(750, 500));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        dungeon.setColumns(20);
        dungeon.setRows(5);
        dungeon.setEnabled(false);
        jScrollPane1.setViewportView(dungeon);

        mapTab.addTab("Dungeon", jScrollPane1);

        map.setColumns(20);
        map.setRows(5);
        jScrollPane2.setViewportView(map);

        mapTab.addTab("Map", jScrollPane2);

        inventory.setColumns(20);
        inventory.setRows(5);
        jScrollPane3.setViewportView(inventory);

        mapTab.addTab("Inventory", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapTab, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapTab, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dungeon;
    private javax.swing.JTextArea inventory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea map;
    private javax.swing.JTabbedPane mapTab;
    // End of variables declaration//GEN-END:variables
}
