/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Render;

/**
 *
 * @author Torri
 */
public class TextRender extends javax.swing.JPanel {

    /**
     * Creates new form TextRender
     */
    public TextRender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapTab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        dungeon = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        map = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        inventory = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(750, 500));

        dungeon.setColumns(20);
        dungeon.setRows(5);
        dungeon.setEnabled(false);
        jScrollPane1.setViewportView(dungeon);

        mapTab.addTab("Dungeon", jScrollPane1);

        map.setColumns(20);
        map.setRows(5);
        jScrollPane2.setViewportView(map);

        mapTab.addTab("Map", jScrollPane2);

        inventory.setColumns(20);
        inventory.setRows(5);
        jScrollPane3.setViewportView(inventory);

        mapTab.addTab("Inventory", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapTab, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapTab, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dungeon;
    private javax.swing.JTextArea inventory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea map;
    private javax.swing.JTabbedPane mapTab;
    // End of variables declaration//GEN-END:variables
}
